name: angular_bloc
description: A web app that uses AngularDart Components
version: 0.1.0
author: Leon Tappe <ltappe@mail.upb.de>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0
  bloc: ^0.6.0

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
  pageloader: ^3.0.0
